services:
  - type: web
    name: telegram-music-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: your-bot-token-goes-here
